export const FETCH_RIDES_REQUEST = 'FETCH_RIDES_REQUEST';
export const FETCH_RIDES_SUCCESS = 'FETCH_RIDES_SUCCESS';
export const FETCH_RIDES_FAILURE = 'FETCH_RIDES_FAILURE';

export const CREATE_RIDE_REQUEST = 'CREATE_RIDE_REQUEST';
export const CREATE_RIDE_SUCCESS = 'CREATE_RIDE_SUCCESS';
export const CREATE_RIDE_FAILURE = 'CREATE_RIDE_FAILURE';

export const FETCH_RIDE_PRICING_REQUEST = 'FETCH_RIDE_PRICING_REQUEST';
export const FETCH_RIDE_PRICING_SUCCESS = 'FETCH_RIDE_PRICING_SUCCESS';
export const FETCH_RIDE_PRICING_FAILURE = 'FETCH_RIDE_PRICING_FAILURE';
