export const NEW_RIDE_REQUEST = 'NEW_RIDE_REQUEST';
export const NEW_DELIVERY_REQUEST = 'NEW_DELIVERY_REQUEST';
export const RIDE_ACCEPTED = 'RIDE_ACCEPTED';
export const RIDE_REJECTED = 'RIDE_REJECTED';
export const DELIVERY_ACCEPTED = 'DELIVERY_ACCEPTED';
export const DELIVERY_REJECTED = 'DELIVERY_REJECTED';
