export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';

export const FETCH_CARD_INITIALIZATION_URL_REQUEST = 'FETCH_CARD_INITIALIZATION_URL_REQUEST';
export const FETCH_CARD_INITIALIZATION_URL_SUCCESS = 'FETCH_CARD_INITIALIZATION_URL_SUCCESS';
export const FETCH_CARD_INITIALIZATION_URL_FAILURE = 'FETCH_CARD_INITIALIZATION_URL_FAILURE';

export const CREATE_CARD_REQUEST = 'CREATE_CARD_REQUEST';
export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';
export const CREATE_CARD_FAILURE = 'CREATE_CARD_FAILURE';

export const SELECT_CARD = 'SELECT_CARD';
